# coding: utf-8

"""
    Autenticação de Usuário API

    API que gerencia a autenticação e autorização de usuários.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.forgot_password_request import ForgotPasswordRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestForgotPasswordRequest(unittest.TestCase):
    """ForgotPasswordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testForgotPasswordRequest(self):
        """Test ForgotPasswordRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.forgot_password_request.ForgotPasswordRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
