# coding: utf-8

"""
    Autenticação de Usuário API

    API que gerencia a autenticação e autorização de usuários.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_user_request import UpdateUserRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateUserRequest(unittest.TestCase):
    """UpdateUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateUserRequest(self):
        """Test UpdateUserRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_user_request.UpdateUserRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
