# coding: utf-8

"""
    Autenticação de Usuário API

    API que gerencia a autenticação e autorização de usuários.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.token_response import TokenResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestTokenResponse(unittest.TestCase):
    """TokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenResponse(self):
        """Test TokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.token_response.TokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
